name = "hanzi-trainer"
account_id = "2331828564d58486402aaaae423355bb"
workers_dev = true
assets = { not_found_handling = "single-page-application" }
compatibility_date = "2025-07-13"
main = "worker/index.ts"

[[r2_buckets]]
binding = 'DATASETS_BUCKET'
bucket_name = 'hanzi'

[observability]
enabled = true

[build]
command = "npm run build"
